[cookie]
name = "carrefour_toolbox_cookie"
key = "WOYnhStkAwkhWO7TS5cBfnOBlj-Lg96q3i47LD2VCek"
expiry_days = 30

[credentials.usernames.admincdg]
email = "admincdg@carrefour.com"
name = "Admin CDG"
password = "$2b$12$7t48YE7FIMOpAaFOk5qgD.OrMx/CY1JTcA8gPSnukuoCbp4DNd24."
